### PR TITLE
Dockerfile: broken plink dl link; use github code instead

### PR DESCRIPTION
**Pull request by f-krull**
Plink download link [1] used in Dockerfile gives 404. 

This PR fetches latest tagged release (2.0 alpha 1 final) from github. plink2 bin is complied and placed in `/usr/bin`.

[1] https://www.cog-genomics.org/static/bin/plink180221/plink_linux_x86_64.zip

### CODE REVIEW

**Comment by oskarvid** [comment]
Plink is now added from a local zip archive instead of compiling or relying on direct download links.

**Comment by f-krull** [comment]
@oskarvid : Can you please reconsider your decision of not accepting this PR or give better arguments? I see that you fixed it by now - but I think my fix adds value and I've already created it. 

1) Github links should be relatively stable + you rely on them elsewhere.
2) Avoiding predownloaded, precompiled binaries is better for reproducibility.

I'll update my PR, if I get Ok from you.

**Comment by oskarvid** [comment]
@f-krull 
I was a unclear in my comment regarding the direct download link, I could have elaborated more in my response, I'm sorry about that.
1. I was referring to the old direct download link to the plink zip archive. The one we used was taken down, so to avoid that issue I figured it would be easier to just store the zip archive in this repository and not have to manage any download links for plink again. 
2. The changes in the repository are tracked so we will notice is the zip archive is changed. I don't see any problems or risks with this.
Another reason to avoid pulling plink from github is because it requires more dependencies to be able to compile which increases the build time and file size of the docker/singularity image.

I hope I was able to clarify my reasons better this time.

**Comment by f-krull** [comment]
Ok, let's stop the discussion. Thanks for your comments.

**Pull request closed without merging**
